### ISSUE TITLE
Работает?

### ISSUE THREAD

**Issue by qweik** [pLavrenov/bitrix-decoder#1]
Работает ли декодер? 
Не чужие закодированные модули, не ваши, которые я нашел в https://github.com/pLavrenov/bitrix-decoder/commit/084b8657e771adf0361e5fd9390f89fb47ff2837, не декодируются. 

Помогите.

**Comment by pLavrenov** [comment]
Работает. Проверил на свежей сборке, файл main/include.php.

Со сторонними модулям может и не работать, т.к они могут другими методами обфусцировать файлы.

**Comment by qweik** [comment]
> main/include.php
Он же не обфусцирован. Этот декодер только для модулей от компании битрикс получается?

**Comment by pLavrenov** [comment]
Полностью обфусцирован в пробных версиях и частично в платных. 

Да, только для стандартных.

**Comment by qweik** [comment]
С виду из маркетплэйса зашифрованы так же. Вручную переменные можно расшифровать, функции тоже. Но это долго. 
Есть какое-то решение?

**Comment by pLavrenov** [comment]
Скинь файлик, попробую. В целом, если алгоритм похожий то можно немного подправить и будет работать.

**Comment by qweik** [comment]
Напишите почту, я скопирую потом удалите из публичного доступа

**Comment by pLavrenov** [comment]
lavrenov.pavel@gmail.com

**Comment by qweik** [comment]
Скопировал

**Comment by pLavrenov** [comment]
Работает. http://prntscr.com/lz4a5v

Местами я немного поленился доделать но думаю в скором времени исправлю такие моменты типа http://prntscr.com/lz4als (разбитых строк), но для дела они не мешают ;)

**Comment by qweik** [comment]
Спасибо за работу!

**Comment by qweik** [comment]
Проблема была в версии php. На 7.1 работает точно
